sumo_joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

sumo_camera_controller:
  type: "position_controllers/JointPositionController"
  joint: base_to_camera

sumo_right_wheel_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: base_to_right_wheel

sumo_left_wheel_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: base_to_left_wheel
